services:
  ia_check_root:
    hostname:         ia_check_root.innovanon.com
    build:
      context:        .
      tags:
        - ia_check_root:latest
    restart:          no
    logging:
      driver:         syslog   
